# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181222_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_info',
            name='introduction',
            field=models.TextField(default='', verbose_name='\u6587\u7ae0\u9884\u89c8'),
        ),
    ]
