# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181224_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='lang',
            field=models.CharField(default='us', max_length=25, verbose_name='\u8bed\u8a00'),
        ),
    ]
