# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tags_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_info',
            name='keyword',
            field=models.CharField(default='', max_length=512, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AddField(
            model_name='categories',
            name='menu_comment',
            field=models.CharField(default='', max_length=512, verbose_name='\u76ee\u5f55\u89e3\u91ca'),
        ),
        migrations.AddField(
            model_name='categories',
            name='menu_url',
            field=models.CharField(default='', max_length=25, verbose_name='\u76ee\u5f55Url\u5b57\u6bb5'),
        ),
    ]
