# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181225_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_info',
            name='product_menu',
            field=models.CharField(default='', max_length=25, verbose_name='\u4ea7\u54c1\u76ee\u5f55'),
        ),
    ]
