# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_info_product_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='menu_keywords',
            field=models.CharField(default='', max_length=512, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='article_info',
            name='url_title',
            field=models.CharField(max_length=256, verbose_name='\u6587\u7ae0url'),
        ),
    ]
